### ISSUE TITLE
terminal changed and autohide left panel

### ISSUE THREAD

**Issue by zeldalf** [WillPower3309/awesome-dotfiles#13]
why did you change terminal back to alacritty again? and is there any way to auto hide the left panel when a program is running?

please forgive my newb questions

**Comment by WillPower3309** [comment]
I changed back to alacritty because I decided I prefer the gpu acceleration it provides over the font ligatures it is missing, both alacritty and kitty are great though!

There isn't a way to autohide the left panel yet, but thats a good idea!

Theres nothing to forgive! I appreciate the feedback and questions :)
